version: "3.8"

services:
  tybalt:
    build: .
    ports:
      - "80:80" # HTTP port for Let's Encrypt challenge
      - "443:443" # HTTPS port
      - "8080:8080" # Fallback HTTP port
    volumes:
      - "./data:/pb/pb_data"
    environment:
      # Add your domain here or pass via command line
      DOMAIN: ${DOMAIN:-}
      # Optional: Set memory limit for constrained environments
      # GOMEMLIMIT: "512MiB"
      # Optional: Encryption key for settings
      # PB_ENCRYPTION_KEY: "your-32-character-encryption-key"
    restart: unless-stopped
    # Override command to use domain if provided
    command: >
      sh -c "
      if [ -n \"$$DOMAIN\" ]; then
        echo \"Starting with HTTPS for domain: $$DOMAIN\"
        ./tybalt serve $$DOMAIN
      else
        echo \"Starting with HTTP only\"
        ./tybalt serve --http=0.0.0.0:8080
      fi
      "
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
