app = "tybalt"
primary_region = "yul"

[build]

[deploy]
  strategy = "immediate"  # Replace machines immediately instead of creating new ones first

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"  # Keep running for database consistency
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  concurrency = { type = "connections", hard_limit = 1000, soft_limit = 800 }

  [[http_service.checks]]
    method = "GET"
    path = "/api/health"
    interval = "30s"
    timeout = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1 