#!/bin/bash

# This script processes the JSON file generated by tybalt and tybalt turbo to
# normalize them for debugging and analysis and to verify that the data is
# consistent and accurate after writeback.

# Script to process JSON files containing arrays of objects with uid and entries properties
# - Sorts outer array by uid
# - Removes rejected, submitted, exported, locked, approved, rejectionReason, id from parent objects
# - Converts payrollId to string in parent objects
# - Sorts main object properties alphabetically
# - Sorts jobNumbers and divisions arrays within each parent object
# - Removes weekEnding and id properties from entry objects
# - Sorts entry object properties alphabetically
# - Sorts entries by timetype, job, client, division, workDescription, date
# Usage: ./process_json.sh input.json

if [ $# -eq 0 ]; then
    echo "Usage: $0 <json_file>"
    exit 1
fi

input_file="$1"

if [ ! -f "$input_file" ]; then
    echo "Error: File '$input_file' not found"
    exit 1
fi

# Create a temporary file for the output
temp_file=$(mktemp)

# Apply the sorting transformation
jq 'sort_by(.uid) | map(del(.rejected, .submitted, .exported, .locked, .approved, .rejectionReason, .id) | .payrollId |= tostring | .entries |= (map(del(.weekEnding, .id) | to_entries | sort_by(.key) | from_entries) | sort_by(.timetype, .job, .client, .division, .workDescription, .date)) | .jobNumbers |= sort | .divisions |= sort | to_entries | sort_by(.key) | from_entries)' "$input_file" > "$temp_file"

# Check if jq succeeded
if [ $? -eq 0 ]; then
    # Move the temp file back to the original file
    mv "$temp_file" "$input_file"
    echo "Successfully sorted '$input_file'"
else
    echo "Error: jq command failed"
    rm "$temp_file"
    exit 1
fi