# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write # Allow pushing commits and tags

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js for version scripts
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Increment build number
        run: |
          chmod +x scripts/increment-version.sh
          ./scripts/increment-version.sh build

      - name: Get version info
        id: version
        run: |
          chmod +x scripts/version.sh
          echo "full_version=$(./scripts/version.sh short)" >> $GITHUB_OUTPUT
          echo "git_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git add version.json
          git commit -m "Bump version to ${{ steps.version.outputs.full_version }}"
          git tag "v${{ steps.version.outputs.full_version }}"

      - name: Push changes
        run: |
          git push origin main
          git push origin "v${{ steps.version.outputs.full_version }}"

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
